
theme = "onedark"

[editor]
color-modes = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false


[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "diagnostics"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type", "selections", "position"]

[keys.normal]

"ret" = ["move_line_down", "goto_first_nonwhitespace"]
# Save file
C-s = ":w"
# Copy + Paste
C-c = "yank"
C-v = "paste_after"
C-V = "paste_before"
# Undo redo
C-z = "undo"
C-Z = "redo"
C-y = "redo"
# Comment toggle
"C-/" = "toggle_comments"
# indent/unindent
"C-[" = "unindent"
"C-]" = "indent"
# Easier deletion in normal mode
"backspace" = "delete_char_backward"
# diagnostics
"C-space" = "code_action"
"C-." = "hover"

[keys.insert]
# save file
C-s = ":w"
# Copy paste
C-c = "yank"
C-v = "paste_after"
C-V = "paste_before"
# Undo redo
C-z = "undo"
C-Z = "redo"
C-y = "redo"
# Comment toggle
"C-/" = "toggle_comments"
# indent/unindent
"C-[" = "unindent"
"C-]" = "indent"
# Diagnostics
"C-space" = "code_action"
"C-." = "hover"
