
theme = "onedark"

[editor]
color-modes = true
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false


[editor.statusline]
left = ["mode", "spacer", "spinner", "spacer", "diagnostics"]
center = ["file-name"]
right = ["file-encoding", "file-line-ending", "file-type", "selections", "position"]

[keys.normal]
"ret" = ["move_line_down", "goto_first_nonwhitespace"]
C-s = ":w"
C-c = "yank"
C-z = "undo"
C-Z = "redo"
C-y = "redo"
"C-/" = "toggle_comments"
"C-[" = "unindent"
"C-]" = "indent"
"backspace" = "delete_char_backward"
"C-space" = "code_action"
"C-." = "hover"

[keys.insert]
C-s = ":w"
C-x = "normal_mode"
C-c = "yank"
C-v = "paste_after"
C-V = "paste_before"
C-z = "undo"
C-Z = "redo"
C-y = "redo"
"C-/" = "toggle_comments"
"C-[" = "unindent"
"C-]" = "indent"
"C-space" = "code_action"
"C-." = "hover"
