
[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

[[language]]
name = "java"
roots = [".gradlew", ".git", "mvnw", "pom.xml"]


[[langauge]]
name = "html"
auto-format = false

