
[[language]]
name = "rust"
auto-format = true
language-server = { command = "rustup", args = ["run", "nightly", "rust-analyzer"]}
config = {checkOnSave = {extraArgs = ["--profile", "rust-analyzer"]}}

[[language]]
name = "java"
roots = [".gradlew", ".git", "mvnw", "pom.xml"]


[[langauge]]
name = "html"
auto-format = false

